### ISSUE TITLE
dev: Handle network error

### ISSUE THREAD

**Issue by HamidMolareza** [HamidMolareza/QueraProblems#4]
When an error occurs, the whole program stops.
We must have error handling to retry failed operations.

An example error:
```
 Unhandled exception. System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Quera.Program.GetQuestionTitle(String link) in /home/runner/work/QueraProblems/QueraProblems/Quera/Program.cs:line 82
   at Quera.Program.CreateReadmeAsync(IEnumerable`1 branches) in /home/runner/work/QueraProblems/QueraProblems/Quera/Program.cs:line 64
   at Quera.Program.Main(String[] args) in /home/runner/work/QueraProblems/QueraProblems/Quera/Program.cs:line 23
   at Quera.Program.<Main>(String[] args)
Processing branch 3029...
Error: Process completed with exit code 134.
```

**Comment by HamidMolareza** [comment]
Fixes with [OnRail](https://github.com/payadel/onrail) library.
